server {
    listen 5000;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # This line is the "magic" for React/SPA routing
        try_files $uri $uri/ /index.html;
    }

    # Optional: Handle Nginx error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
