server {
    listen 80;

    # Route to Frontend
    location / {
        proxy_pass http://web-client:5000; # Matches the new frontend port
        proxy_set_header Host $host;
    }

    # Route to Backend API
    location /api/ {
        proxy_pass http://api-server:3000; # Matches your backend EXPOSE
        proxy_set_header Host $host;
    }
}
