server {
    listen 10000;

    location /api/ {
        proxy_pass https://meeting-room-request-system-0awa.onrender.com;
        proxy_set_header Host meeting-room-request-system-0awa.onrender.com;
        proxy_ssl_server_name on;
    }

    location / {
        proxy_pass https://meeting-room-request-system.onrender.com;
        proxy_set_header Host meeting-room-request-system.onrender.com;
        proxy_ssl_server_name on;
    }
}
